import * as ccc from '@ckb-ccc/core';
import { readFileSync, writeFileSync } from 'node:fs';
import { createPudgeClient, committedTransaction } from '../src/ckbfs/client';
import { assertRegistryTransition, decodeRegistry, registryCatalog } from '../src/registry/registry';
import { JUKEBOX_CONFIG } from '../config/jukebox';
const [hash, previousEvidence, manifestEvidence, output] = process.argv.slice(2);
if (!hash || !previousEvidence || !manifestEvidence || !output) throw Error('Usage: hash previous-evidence manifest-evidence output-evidence');
const prior = JSON.parse(readFileSync(previousEvidence, 'utf8'));
const target = JSON.parse(readFileSync(manifestEvidence, 'utf8'));
const client = createPudgeClient();
const tx = await committedTransaction(client, hash as ccc.Hex);
const old = await committedTransaction(client, prior.txHash);
const previous = { typeId: JUKEBOX_CONFIG.registryTypeId!, cell: ccc.Cell.from({ outPoint: { txHash: prior.txHash, index: 0 }, cellOutput: old.outputs[0], outputData: old.outputsData[0] }), data: decodeRegistry(ccc.bytesFrom(old.outputsData[0])) };
const expected = { version: 1 as const, revision: previous.data.revision + 1n, manifestTypeId: target.typeId, manifestHash: target.contentHash };
assertRegistryTransition(tx, { typeId: previous.typeId, previous, data: expected, ownerLock: previous.cell.cellOutput.lock });
const catalog = await registryCatalog(previous.typeId, client);
if (catalog.registry.cell.outPoint.txHash !== hash || catalog.manifest.pointer.typeId !== target.typeId || catalog.manifest.pointer.contentHash !== target.contentHash) throw Error('Live registry/catalog does not match the signed update');
const evidence = { txHash: hash, typeId: previous.typeId, status: 'committed', revision: expected.revision.toString(), manifestTypeId: expected.manifestTypeId, manifestHash: expected.manifestHash, ownerLockHash: tx.outputs[0].lock.hash(), previousTxHash: prior.txHash, typeIdPreserved: true, ownerLockPreserved: true, exactPreviousConsumed: true, manifestVerified: true, checkedAt: new Date().toISOString() };
writeFileSync(output, JSON.stringify(evidence, null, 2) + '\n'); console.log(JSON.stringify(evidence, null, 2));
